In [21]:
from scipy import stats
from scipy.stats import chi2_contingency
import numpy as np
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/it-ces/labHealth/master/database.csv")

In [22]:
n,p = stats.shapiro(df['var3'])
if p<0.05:
  print('no normal variable')

no normal variable

In [23]:
df

    Unnamed: 0        var1    var2      var3  var4
0            0  no disease  Female  1.355427    58
1            1     disease    male  0.805698    40
2            2  no disease  Female  0.029375    49
3            3     disease    male  0.681085    45
4            4  no disease    male  1.909778    25
..         ...         ...     ...       ...   ...
95          95     disease    male  1.350235    52
96          96     disease  Female  0.074994    50
97          97  no disease  Female  0.935725    56
98          98  no disease    male  0.225422    26
99          99     disease  Female  0.583728    43

[100 rows x 5 columns]

In [26]:
contigency= pd.crosstab(df['var1'], df['var2'])

In [28]:
contigency

var2        Female  male
var1
disease         29    26
no disease      23    22

In [38]:
contigency_pct = pd.crosstab(df['var1'], df['var2'], normalize='index')
contigency_pct    # normalize options are index, columns, all
c, p, dof, expected = chi2_contingency(contigency) 
# Print the p-value
print(p)
# p < 0.05 reject the null hypothesis; this means that are not indepedent!

1.0

In [ ]:
# Whats means p-value in this context?

In [40]:
contigency

var2        Female  male
var1
disease         29    26
no disease      23    22